In [1]:
import numpy as np

In [2]:
# Из обычного списка
sp=np.array([1,2,3,4,5])
print("Массив из списка:",sp)

# С использованием встроенных функций
arr_zeros=np.zeros(5)               # массив из 5 нулей
arr_ones=np.ones((2,3))            # матрица 2x3 из единиц
arr_arange=np.arange(0,10,2)      # [0, 2, 4, 6, 8]

print("\nМассив из нулей:",arr_zeros)
print("\nМатрица из единиц:\n",arr_ones)
print("\nМассив через arange:",arr_arange)

Массив из списка: [1 2 3 4 5]

Массив из нулей: [0. 0. 0. 0. 0.]

Матрица из единиц:
 [[1. 1. 1.]
 [1. 1. 1.]]

Массив через arange: [0 2 4 6 8]


In [3]:
# Возьмём  матрицу из единиц
print("Форма:",arr_ones.shape)
print("Тип данных:",arr_ones.dtype)

Форма: (2, 3)
Тип данных: float64


In [4]:
# Создадим одномерный массив
mark=np.array([1,2,3,4,5])

# Получение отдельного элемента (второй элемент, индекс 1)
element=mark[1]
print("Оценка по индексу 1:",mark)

# Извлечение подмассива с помощью среза (элементы с индекса 1 до 4, не включая 4)
srez=mark[1:4]
print("Срез [1:4]:",srez)

# Пример для двумерного массива
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])

# Получить элемент во второй строке, третьем столбце (индексы [1, 2])
element_21=matrix[1,2]
print("Элемент [1,2] в матрице:",element_21)

# Срез строк: первые две строки
srezmatrix=matrix[:2, :]
print("Первые две строки:\n",srezmatrix)

Оценка по индексу 1: [1 2 3 4 5]
Срез [1:4]: [2 3 4]
Элемент [1,2] в матрице: 6
Первые две строки:
 [[1 2 3]
 [4 5 6]]


In [5]:
# Два массива для операций
a=np.array([1, 2, 3, 4])
b=np.array([5, 6, 7, 8])

# Поэлементное умножение
multiply=a*b
print("Поэлементное умножение:",multiply)

# Поэлементное сложение
summa=a+b
print("Поэлементное сложение:",summa)

# Векторная операция: возведение в квадрат
squared=a**2
print("Квадраты элементов a:", squared)

# Статистика: среднее значение
sred=np.mean(b)
print("\nСреднее значение массива b:",sred)

# Другие полезные статистики
max_b=np.max(b)
std_a=np.std(a)

print("Максимум b:",max_b)
print("Стандартное отклонение a:",std_a)

Поэлементное умножение: [ 5 12 21 32]
Поэлементное сложение: [ 6  8 10 12]
Квадраты элементов a: [ 1  4  9 16]

Среднее значение массива b: 6.5
Максимум b: 8
Стандартное отклонение a: 1.118033988749895
